hmcts/rd-judicial-api

build.gradle
charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.yaml

fix: master sonar fix

---

Jenkinsfile_CNP
charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.preview.template.yaml
charts/rd-judicial-api/values.yaml

NA
fix:  removed depreciation in values yaml and jenkins
No

fix:  removed depreciation in values yaml and jenkins

---

database/Dockerfile
infrastructure/main.tf
infrastructure/variables.tf

Dbmigration version 9.6 to 11
```
[ ] Yes
[ X] No
```

Dbmigration version v11

---

src/main/resources/db/migration/V1_3__insert_judicialrole_type.sql

added judicial role type to since foreign key is required for appointment table
```
[ ] Yes
[X] No
```

added judicial role type to since foreign key is required for appointment table

---

infrastructure/main.tf

database upgrade from 9.6 to v11
```
[ ] Yes
[X ] No
```

updating db version to 11 .

---

infrastructure/output.tf

refactor: updated output.tf

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/requirements.yaml

config:updated chart version

---

Jenkinsfile_nightly
build.gradle
src/main/resources/db/migration/V1_4__alter_jrd_tables.sql
src/main/resources/db/migration/V1_5__defult_insert_leaf_tables.sql
src/main/resources/db/migration/V1_6__excption_table.sql
src/main/resources/db/migration/V1_7__audit_table.sql
src/main/resources/db/migration/V1_8__delete_judicialrole_type_insert.sql

https://tools.hmcts.net/jira/browse/RDCC-1223
feat:schema updates for JRD JSR and Auditing(RDCC-1223)
No

feat:schema updates for JRD JSR and Auditing(RDCC-1223)

---

charts/rd-judicial-api/Chart.yaml

NA
refactor: bump up JRD charts
No

refactor: bump up JRD charts

---

src/main/resources/db/migration/V1_9__defult_insert_leaf_tables_not_exists.sql

refactor: flyway update

---

src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/DataSourceConfig.java
src/main/resources/application.yaml

NA
fix: datasource connection settings updated
No

fix: datasource connection settings updated

---

Jenkinsfile_CNP
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RDCC-1286
fix: Demo aks changes
No

fix: Demo aks changes

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-1336
Change description
refactor: Suppression xml cleanup (RDCC-1336)
Does this PR introduce a breaking change? (check one with "x")
No

refactor: Suppression xml cleanup (RDCC-1336)

---

Jenkinsfile_CNP
Jenkinsfile_parameterized

https://tools.hmcts.net/jira/browse/RDCC-1440
removing installCharts() from Jenkinsfiles
```
[ ] Yes
[x] No
```

RDCC-1440: removing installCharts() from Jenkinsfiles

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-1713
fix: flyway fix for java 11
No

fix: flyway fix for java 11

---

build.gradle
config/owasp/suppressions.xml
src/smokeTest/java/uk/gov/hmcts/reform/judicialapi/SmokeTest.java

https://tools.hmcts.net/jira/browse/RDCC-1742
fix:clean up suppressions (RDCC-1740)
No

fix:clean up suppressions (RDCC-1740)

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-1757
fix:PI Mutation plugin update
No

fix:PI Mutation plugin update(RDCC-1757)

---

src/main/resources/db/migration/V1_11__drop_and_recreate_auth_table.sql

RDCC-1695
RDCC-1695: Updating auth table
```
[ ] Yes
[X] No
```

RDCC-1695: Updating auth table

---

build.gradle
src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java

fix: Nightly build fix

---

build.gradle

RDCC-1933
This PR covers jar bump ups and owasp update
```
[ ] Yes
[X ] No
```

Fix : Jar bumps up and owasp update(RDCC-1933)

---

config/owasp/suppressions.xml

feat:nightly build fix
```
[ ] Yes
[X ] No
```

adding suppressions to fix the build

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/requirements.yaml

Not available
```
[ ] Yes
[X] No
```

Update java chart version - Master

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-2143
CVE-2020-8908: Fixing the CVE.
```
[ ] Yes
[x] No
```

CVE-2020-8908: Fixing the CVE.

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.preview.template.yaml
charts/rd-judicial-api/values.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/RDCC-2141
```
[ ] Yes
[X] No
```

Update s2s secret reference

---

infrastructure/main.tf

Reverts hmcts/rd-judicial-api#87

Revert "Delete unused secrets"

---

src/main/resources/db/migration/V1_13__alter_judicial_user_profile.sql

RDCC-2410
This change will add additional column Object ID in Judicial User profile table
```
[ ] Yes
[ X] No
```

feat: Added Object ID column in db script(RDCC-2410)

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/requirements.yaml
charts/rd-judicial-api/values.preview.template.yaml
charts/rd-judicial-api/values.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```

Update app insights key secret name

---

charts/rd-judicial-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-2746
Helm chart version updated
```
[ ] Yes
[X ] No
```

fix:RDCC-2746-Helm chart version updated

---

build.gradle

upgraded springboot version from 2.4.5 to 2.4.6 to fix cvv

---

src/integrationTest/resources/db/testmigration/V1_16__create_mapping_tables.sql
src/main/resources/db/migration/V1_16__create_mapping_tables.sql

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-2875
&
https://tools.hmcts.net/jira/browse/RDCC-2919
Change description
Create and Insert Data into Mapping tables for IAC locations for the Service code BFA1
```
[ ] Yes
[x] No
```

Feat: RDCC-2875/2919; Create and Insert Data into Mapping tables for IAC locations for the Service code BFA1

---

Jenkinsfile_nightly

added config for serenity report in nightly job

---

security.sh

change the sequence in security.sh to fix security scan

---

build.gradle

RDCC-3141: fixed CVE

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3150
Update repositories reference to Jitpack
```
[ ] Yes
[X] No
```

RDCC-3150 - Update repositories reference to Jitpack

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/RDCC-2963
Added configuration to the `Jenkinsfile_nightly` to fix nightly build failure
```
[ ] Yes
[x] No
```

RDCC-2963_nightly_fix: Add config to fix nightly build failure

---

src/main/resources/db/migration/V1_21__alter_judicial_office_authorisation.sql

https://tools.hmcts.net/jira/browse/RDCC-3038
JRD : Add Service code column to Authorization table
```
[ ] Yes
[X] No
```

FEAT: JRD : Add Service code column to Authorisations table

---

src/main/resources/db/migration/V1_22__alter_judicial_office_appointment.sql

https://tools.hmcts.net/jira/browse/RDCC-3039
JRD : Add ePIMS ID column to judicial_office_appointment table
```
[ ] Yes
[X] No
```

Feat:JRD - Add ePIMS ID column to judicial_office_appointment table

---

charts/rd-judicial-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-3169
Update chart versions in all PRD repos
```
[ ] Yes
[X] No
```

RDCC-3169 - Update chart versions in all PRD repos

---

build.gradle
config/owasp/suppressions.xml

RDCC-3237
This change will address the Jakarta CVE
```
[ ] Yes
[ X] No
```

fix: Fix CVE for Jakarta(RDCC-3237)

---

config/owasp/suppressions.xml

fixed dependency check

---

src/main/resources/db/migration/V1_24__alter_dataload_exception_records_add_row_id.sql

https://tools.hmcts.net/jira/browse/RDCC-3230
Added flyway script for new row_id column in exception table
```
[ ] Yes
[x] No
```

feat: RDCC-3230 Added flyway script for new row_id column in exception table

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
bin/run-in-docker.sh
charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.preview.template.yaml
charts/rd-judicial-api/values.yaml
src/functionalTest/resources/application-functional.yaml
src/integrationTest/resources/application.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-3277
Removed hard coded string in the configuration files.
```
[ ] Yes
[x] No
```

RDCC-3277: Removed hard coded string in the configuration files.

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/client/JudicialApiClient.java
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/LaunchDarklyConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/TestingSupportController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/feign/IdamUserFeignClient.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/request/RoleDetail.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/request/TestUserRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/IdamUserProfileResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/repository/IdamUserProfileRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/repository/UserProfileRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/IdamUserProfileService.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/JudicialUserService.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/FeatureToggleServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/IdamUserProfileServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/util/JrdConstant.java
src/main/java/uk/gov/hmcts/reform/judicialapi/util/RefDataUtil.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-3511
JRD : SIDAM User creation for all object IDs
```
[ ] Yes
[ ] No
```

Feat:SIDAM User creation for all object IDs

---

audit.json
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/TestingSupportController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/request/TestUserRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/IdamUserProfileServiceImpl.java

https://tools.hmcts.net/jira/browse/RDCC-3511
JRD : SIDAM User creation for all object IDs
```
[ ] Yes
[ X] No
```

Feat:JRD : SIDAM User creation for all object IDs

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-3644
Extended CVE suppression
```
[ ] Yes
[x] No
```

RDCC-3644: JRD CVE suppression extension

---

Jenkinsfile_CNP
Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3677
Publish Jenkins Report
```
[ ] Yes
[X] No
```

Publish Jenkins Report

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.yaml
config/owasp/suppressions.xml
src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/IntegrationTestOidcSecurityConfig.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-1754
https://tools.hmcts.net/jira/browse/RDCC-3619
Replace deprecated methods with new (Java 8 to Java 11 migration)
[ ] Yes
[X ] No

RDCC-1754: Replace deprecated methods with new (Java 8 to Java 11 migration)

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_29__insert_refreshUser_testing.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-3643
Added code changes to populate only active roles and the necessary junit and integration tests
```
[ ] Yes
[X ] No
```

Code Changes for populating only active roles in judicial refresh api

---

build.gradle
config/owasp/suppressions.xml

Jira Link: https://tools.hmcts.net/jira/browse/RDCC-3946

RDCC-3946: CVE fixes

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3923
Removed deprecated jcenter repository
```
[ ] Yes
[x] No
```

RDCC-3923: JRD-api Remove Deprecated Jcenter Repository

---

src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/RestAuthenticationEntryPoint.java
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SecurityConfiguration.java

https://tools.hmcts.net/jira/browse/RDCC-3449
https://tools.hmcts.net/jira/browse/RDCC-3449
```
[ ] Yes
[x] No
```

logged idam bearer token exception

---

build.gradle
charts/rd-judicial-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-4056
fix: Bump base java helm chart to 3.7.1 
```
[ ] Yes
[x] No
```

fix: Bump base java helm chart to 3.7.1

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4088
Fix nightly build failure due to CWE-862: Missing Authorization
```
[ ] Yes
[x] No
```

fix: RDCC-4088 Fix nightly build failure due to CWE-862: Missing Authorization

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/JudicialUsersFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/client/JudicialApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/FetchUsersIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/wiremock/WireMockExtension.java

https://tools.hmcts.net/jira/browse/RDCC-4029
JRD: Completeness of functional and Integration test
```
[ ] Yes
[X] No
```

Enhanced functional and integration test cases

---

src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/JudicialUsersFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/client/JudicialApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_29__insert_refreshUser_testing.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/repository/UserProfileRepository.java

https://tools.hmcts.net/jira/browse/RDCC-4138
https://tools.hmcts.net/jira/browse/RDCC-4138
```
[ ] Yes
[x] No
```

updated sql query

---

build.gradle
src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/util/FeatureConditionEvaluationTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/util/RequestUtilsTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/validator/RefreshUserValidatorTest.java

https://tools.hmcts.net/jira/browse/RDCC-4173
fix: Resolved PACT provider failure by mocking all the values
```
[ ] Yes
[x] No
```

fix: Resolved PACT provider failure by mocking all the values

---

charts/rd-judicial-api/Chart.yaml
src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java

https://tools.hmcts.net/jira/browse/RDCC-4139
Updated java chart version to 3.7.2
```
[ ] Yes
[x] No
```

fix: Updated java chart version to 3.7.2

---

src/main/java/uk/gov/hmcts/reform/judicialapi/controller/advice/ExceptionMapper.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/advice/ExceptionMapperTest.java

https://tools.hmcts.net/jira/browse/RDCC-4142
Catched the Exception ,by giving proper error message
```
[ ] Yes
[X ] No
```

exception handled for 4142

---

build.gradle
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/AppointmentRefreshResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/AuthorisationRefreshResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/LrdOrgInfoServiceResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/UserProfileRefreshResponse.java

JRD : fix CVE-2020-36518

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/wiremock/WireMockExtension.java

https://tools.hmcts.net/jira/browse/RDCC-4317
Updated wiremock setup
```
[ ] Yes
[x] No
```

RDCC-4317: JRD API - Improve integration test case timings 

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4427
```
[ ] Yes
[X] No
```

Nightly Build failure issues

---

src/main/resources/db/migration/V1_31__update_jrd_tables.sql

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-4342
Change description
JRD : Update the Service Code & Ticket Code mapping table for SSCS Service
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

JRD : Update the Service Code & Ticket Code mapping table for SSCS Service

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4504
JIRA link (if applicable)
fix for cve 2022-22968
Change description
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

JRD API -Nightly build failure -25/04/2022 

---

src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/util/RefDataUtil.java
src/main/java/uk/gov/hmcts/reform/judicialapi/validator/RefreshUserValidator.java

https://tools.hmcts.net/jira/browse/RDCC-4538
Judicial Reference API Master Build Failure Fix
```
[ ] Yes
[x ] No
```

Feat:Judicial Reference API Master Build Failure Fix

---

build.gradle

CVE Fix for tomcat embed
```
[ ] Yes
[X] No
```

CVE Fix for tomcat embed core n websocket

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/AuthorisationRefreshResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java

JRD : Update the JRD Refresh API to make Service Code as an array
```
[ ] Yes
[X] No
```

JRD : Update the JRD Refresh API to make Service Code as an array

---

Dockerfile
acb.tpl.yaml

https://tools.hmcts.net/jira/browse/RDCC-4781
Added multi-architecture ACR Task template
```
[ ] Yes
[x] No
```

feat: RDCC-4781 Added multi-architecture ACR Task template

---

src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SecurityEndpointFilter.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/advice/UnauthorizedException.java
src/main/java/uk/gov/hmcts/reform/judicialapi/repository/IdamRepository.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/advice/UnauthorizedExceptionTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/repository/IdamRepositoryTest.java

https://tools.hmcts.net/jira/browse/RDCC-4680
To handle 500 HTTP responses
```
[ ] Yes
[x ] No
```

Feat:To handle 500 HTTP responses

---

.github/workflows/combine-prs.yml

https://tools.hmcts.net/jira/browse/RDCC-4844
added git hub workflow to auto merge renovate PRs
```
[ ] Yes
[x] No
```

config: RDCC-4844 added git hub workflow to auto merge renovate PRs

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4948
Altered the mutation threshold
```
[ ] Yes
[x] No
```

fix: RDCC-4948 Altered the mutation threshold

---

src/integrationTest/resources/db/testmigration/V1_35__update_ticket_code_mapping.sql
src/main/resources/db/migration/V1_35__update_ticket_code_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-4959
Update the Ticket Code mapping table
```
[ ] Yes
[x ] No
```

Feat:RDCC-4959:Changes made to update ticket_code mapping

---

charts/rd-judicial-api/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-5007
Adding Suppression for `CVE-2022-34305`
```
[ ] Yes
[x] No
```

RDCC-5007: Adding Suppression for `CVE-2022-34305`

---

src/integrationTest/resources/db/testmigration/V1_36__update_judicial_location_mapping.sql
src/main/resources/db/migration/V1_36__update_judicial_location_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-5000
Updated epimms id of location mapping
```
[ ] Yes
[x] No
```

RDCC-5000: Update the Base Location to ePIMS ID mapping table

---

charts/rd-judicial-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-5145
Upgrade java chart version
```
[ ] Yes
[x] No
```

RDCC-5145 Upgrade java chart version

---

charts/rd-judicial-api/values.preview.template.yaml
src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
src/integrationTest/resources/application.yml
src/main/java/uk/gov/hmcts/reform/judicialapi/repository/UserProfileRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-5136
JRD-API : Configure the serviceCode from cnp-flux
```
[ ] Yes
[X] No
```

RDCC-5136 Configure the serviceCode from cnp-flux

---

config/owasp/suppressions.xml

Address CVE-2021-28170

---

src/integrationTest/resources/db/testmigration/V1_38__update_judicial_service_code_mapping.sql
src/main/resources/db/migration/V1_38__update_judicial_service_code_mapping.sql

Judicial - Update Ticket Code to Service Code mapping for Family Private Law & Adoption Service

---

src/integrationTest/resources/db/testmigration/V1_40__update_judicial_service_code_mapping.sql
src/main/resources/db/migration/V1_40__update_judicial_service_code_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-5738
Update the Judicial Service Code mapping table for Family Public Law & Financial Remedy Services
```
[ ] Yes
[ x] No
```

Feat:RDCC-5738:RDCC-5738:JRD : Update the Judicial Service Code mapping table for Family Public Law & Financial Remedy Services

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/docs/SwaggerPublisherTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/JudicialApiPostgresqlContainer.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/SpringBootIntegrationTest.java
src/integrationTest/resources/application-test.yml

https://tools.hmcts.net/jira/browse/RDCC-5817
Containerisation of integration test cases
```
[ ] Yes
[x ] No
```

Feat:Containerisation of integration test cases

---

src/integrationTest/resources/db/testmigration/V1_50__elinks_alter_tables.sql
src/main/resources/db/migration/V1_50__elinks_alter_tables.sql

https://tools.hmcts.net/jira/browse/RDCC-6048
Make Id columns in appointments , authorisation tables as auto inrement
```
[ ] Yes
[x ] No
```

Feat:RDCC-6048:Altered tables for elinks people api

---

src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/LaunchDarklyConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/FeatureToggleServiceImpl.java

https://tools.hmcts.net/jira/browse/RDCC-6066
Add LaunchDarkly flag for elinks API endpoints
```
[ ] Yes
[X] No
```

Elinks launchdarkly flag

---

src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ElinkSchedularAuditRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataIngestionSchedularAudit.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/ElinkDataSchedularAuditTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataIngestionSchedularAuditTest.java

https://tools.hmcts.net/jira/browse/RDCC-6088
```
[ ] Yes
[X] No
```

eLinks : Write audit utility method for updating dataload_schedular_audit table : RDCC - 6088

---

src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java

Rdcc 6080 fix3

---

build.gradle
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/SqlConstants.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6128
eLinks : Create an elastic search API to call IDAM with a Judiciary role
```
[ ] Yes
[X ] No
```

change the implementation for IDM search query

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LocationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java

https://tools.hmcts.net/jira/browse/RDCC-6081
Added integration tests
```
[ ] Yes
[x] No
```

RDCC-6081: eLinks - Integration Test Cases for Locations API

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/NegativeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java

https://tools.hmcts.net/jira/browse/RDCC-6134
Negative scenarios to be covered in Functional Test
```
[ ] Yes
[ x] No
```

Feat:RDCC-6134:Changes made to add negative integration test  cases

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/IdamElasticSearchIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/NegativeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java
src/integrationTest/resources/db/testmigration/V1_49__elinks_alter_dataload_schedular_audit.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/IdamElasticSearchService.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksControllerTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java

Added the integration test cases

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/NegativeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java

https://tools.hmcts.net/jira/browse/RDCC-6134
Negative scenarios to be covered in Functional Test
```
[ ] Yes
[ x] No
```

Feat:RDCC-6134:Negative scenarios to be covered in Functional Test

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LocationsIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6163
eLinks :Auditing functionality for Locations API
```
[ ] Yes
[x ] No
```

Feat:RDCC-6163:eLinks :Auditing functionality for Locations API

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/BaseLocationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/NegativeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksBaseLocationServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6082
Added audit functionality and integration tests
```
[ ] Yes
[x] No
```

RDCC-6082: eLinks : Integration Test Cases & Auditing functionality for Base Locations API

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LeaversIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/NegativeIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_49__elinks_alter_dataload_schedular_audit.sql
src/integrationTest/resources/db/testmigration/V1_50__elinks_alter_tables.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/ElinkDataExceptionRecords.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ElinkDataExceptionRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataExceptionHelper.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/main/resources/db/migration/V1_49__elinks_alter_dataload_schedular_audit.sql
src/main/resources/db/migration/V1_50__elinks_alter_tables.sql
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java

Appointments exclusion 
```
[ ] Yes
[X] No
```

Rdcc exclude appointments

---

build.gradle
charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.preview.template.yaml
charts/rd-judicial-api/values.yaml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/NegativeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PublishSidamIdIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java
src/integrationTest/resources/application-test.yml
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/ElinkEmailConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/ElinkMessagingConfig.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/PublishingData.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/SendGridConfig.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/SchedulerJobStatusResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/IEmailService.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/PublishSidamIdService.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/dto/Email.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/exception/EmailFailureException.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/EmailServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/PublishSidamIdServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/servicebus/ElinkTopicPublisher.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/JobStatus.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataConstants.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/SqlContants.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/EmailServiceTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/PublishSidamIdServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/servicebus/ElinkTopicPublisherTest.java

https://tools.hmcts.net/jira/browse/RDCC-6102
https://tools.hmcts.net/jira/browse/RDCC-6084
https://tools.hmcts.net/jira/browse/RDCC-6192
eLinks : Integration Test Cases for ASB Publishing logic
eLinks : Publishing the SIDAM ids to Azure Service Bus for Org role mapping for PR Environment Testing
eLinks : Update the status of the ASB publishing task in dataload_scheduler_job table.
```
[ ] Yes
[X] No
```

 Publishing the SIDAM ids to Azure Service Bus

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/BaseLocationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/IdamElasticSearchIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LeaversIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LocationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/NegativeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/SchedulerElinksJobIntegrationTest.java
src/integrationTest/resources/application-test.yml
src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/SchedulerConfig.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobSchedulerTest.java

https://tools.hmcts.net/jira/browse/RDCC-6222
eLinks - Cleanup of temporary data from Integration & functional test cases
```
[ ] Yes
[ x] No
```

Feat:eLinks - Cleanup of temporary data from Integration & functional test cases

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-6222
To fix sonar code coverage issue
```
[ ] Yes
[x ] No
```

Feat:RDCC-SonarCodeIssue:To fix code coverage issue

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-6222
To fix sonar code issue
```
[ ] Yes
[ x] No
```

Feat:To fix sonar code issue

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-6222
To fix sonar code issue
```
[ ] Yes
[ x] No
```

Feat:To fix sonar code coverage

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinkClientsCommonIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/SchedulerElinksJobIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/PublishSidamIdServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java

https://tools.hmcts.net/jira/browse/RDCC-6215
```
[ ] Yes
[X] No
```

ASB Publishing Final Adding to Schedular

---

src/integrationTest/resources/db/testmigration/V1_49__elinks_alter_tables.sql
src/integrationTest/resources/db/testmigration/V1_50__elinks_create_dataload_schedular_job.sql
src/main/resources/db/migration/V1_49__elinks_alter_tables.sql
src/main/resources/db/migration/V1_50__elinks_create_dataload_schedular_job.sql

https://tools.hmcts.net/jira/browse/RDCC-6027
eLinks : Update the tables for Judicial Reference Data
```
[ ] Yes
[x ] No
```

Feat:RDCC-6027:Changes made to merge code to master

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/SchedulerElinksJobIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_49__elinks_alter_dataload_schedular_audit.sql
src/integrationTest/resources/db/testmigration/V1_50__elinks_alter_tables.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/ElinkDataExceptionRecords.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/DataloadSchedulerJobRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ElinkDataExceptionRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataExceptionHelper.java
src/main/resources/db/migration/V1_49__elinks_alter_dataload_schedular_audit.sql
src/main/resources/db/migration/V1_50__elinks_alter_tables.sql
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ElinkDataExceptionRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataExceptionHelperTest.java

https://tools.hmcts.net/jira/browse/RDCC-6319
eLinks : Restrict the duplicate insert for Job Status
**Does this PR introduce a breaking change?**
```
[ ] Yes
[ X] No
```

eLinks : Restrict the duplicate insert for Job Status

---

Dockerfile
build.gradle
charts/rd-judicial-api/Chart.yaml
config/owasp/suppressions.xml
src/functionalTest/resources/application-functional.yaml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/FetchUsersIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/docs/SwaggerPublisherTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/JudicialReferenceDataClient.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/JwtTokenUtil.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/KeyGenUtil.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/SpringBootIntegrationTest.java
src/integrationTest/resources/application-test.yml
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/JrdUsersController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/TestingSupportController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/WelcomeController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/request/UserSearchRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/oidc/JwtGrantedAuthoritiesConverter.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/oidc/JwtGrantedAuthoritiesConverterTest.java

https://tools.hmcts.net/jira/browse/RDCC-6225
Spring Boot Upgrade 2.7.7 and other libraries
```
[ ] Yes
[x] No
```

Rdcc 6225 spring boot upgrade 2.7.7

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-6364
Adding entry to `audit.json` to fix Security Scan stage in Nightly Build
```
[ ] Yes
[x] No
```

RDCC-6364: Adding entry to `audit.json`

---

.github/renovate.json
Dockerfile

https://tools.hmcts.net/jira/browse/RDCC-6407
Upgrade : 
1. APP_INSIGHTS_AGENT_VERSION to 3.4.9
2. renovate.json
```
[ ] Yes
[x] No
```

Upgrade : APP_INSIGHTS_AGENT_VERSION to 3.4.9

---

.github/renovate.json
Dockerfile
build.gradle

https://tools.hmcts.net/jira/browse/RDCC-6407
Upgrade
id 'org.owasp.dependencycheck' version '8.0.2'
```
[ ] Yes
[ ] No
```

Rdcc 6407 renovate and app insight

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/BaseLocationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinkClientsCommonIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_50__elinks_alter_tables.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataIngestionSchedularAuditTest.java

https://tools.hmcts.net/jira/browse/RDCC-6133
We need to exclude appointment for base_location not found in static table
```
[ ] Yes
[ x] No
```

RDCc-Final fix

---

charts/rd-judicial-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/EmailServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/PublishSidamIdServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/servicebus/ElinkTopicPublisher.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/EmailServiceTest.java

Rdcc 6215 401

---

Dockerfile
build.gradle
charts/rd-judicial-api/values.yaml
lib/applicationinsights.json
web.config

https://tools.hmcts.net/jira/browse/RDCC-6407
Judicial Ref Data API - APP INSIGHT
```
[ ] Yes
[x] No
```

Upgrade : versions.reformLogging to 6.0.1

---

charts/rd-judicial-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-6374
Upgrading chart version to ` 4.0.13`
```
[ ] Yes
[x] No
```

RDCC-6374: Upgrading chart version to 4.0.13

---

config/owasp/suppressions.xml
src/integrationTest/resources/db/testmigration/V1_52__alter_judicial_appointment.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/AppointmentsRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/Appointment.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/main/resources/db/migration/V1_52__alter_judicial_appointment.sql
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6434
This Jira will facilitate the removal of the work_pattern field from Judicial_Office_Appointment table. This field is being deprecated & will not longer be present in eLinks V5.0. 
```
[ ] Yes
[x] No
```

RDCC-6434 removing column from table

---

build.gradle
config/owasp/suppressions.xml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-6234
[RDCC-6234] Address CVEs in all Reference Data repositories - Judicial Reference Data
```
[ ] Yes
[x ] No
```

[RDCC-6234] Address CVEs in all Reference Data repositories - Judicial Reference Data

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-6234
Address CVEs in all Reference Data repositories - Judicial Reference Data
```
[ ] Yes
[x ] No
```

[RDCC-6234] -Fix for CVE-2023-24998

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksEnabledIntegrationTest.java

https://tools.hmcts.net/jira/browse/RDCC-6435
```
[ ] Yes
[X] No
```

initial test for populate the value

---

src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataExceptionHelperTest.java

https://tools.hmcts.net/jira/browse/RDCC-6540
```
[ ] Yes
[X] No
```

Typo Error change

---

src/main/java/uk/gov/hmcts/reform/judicialapi/controller/JrdUsersController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/WelcomeController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/oidc/JwtGrantedAuthoritiesConverter.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/advice/UnauthorizedExceptionTest.java

Addressing Sonar Issues
```
[ ] Yes
[X] No
```

Addressing Sonar Issues

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-6609
Suppress CVE-2022-1471
```
[ ] Yes
[X] No
```

RDCC-6609 - suppress CVE-2022-1471

---

config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinkClientsCommonIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/IdamElasticSearchIntegrationTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java

RDCC-6544
Added comments and dummy values for unit tests
```
[ ] Yes
[x ] No
```

fix: Enhancement for unit and inetgration test cases

---

src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/UserSearchResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/repository/UserProfileRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/TestSupport.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6625
[RDCC-6625]Update the SQL query to fetch only the required fields
```
[ ] Yes
[ x] No
```

[RDCC-6625]Update the SQL query to fetch only the required fields

---

config/owasp/suppressions.xml

cve for dev branch local develope only

cve for dev branch

---

src/integrationTest/resources/db/testmigration/V1_56__elinks_shed_scheduler_table.sql
src/main/resources/db/migration/V1_56__elinks_shed_scheduler_table.sql

https://tools.hmcts.net/jira/browse/RDCC-6704
[RDCC-6704]Added Flyway script as part of user story to sync all repo
```
[ ] Yes
[x ] No
```

[RDCC-6704]Added Flyway script as part of user story to sync all repo

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/resources/db/testmigration/V1_56__elinks_shed_scheduler_table.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/SchedulerConfig.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
src/main/resources/application.yaml
src/main/resources/db/migration/V1_56__elinks_shed_scheduler_table.sql

https://tools.hmcts.net/jira/browse/RDCC-6704
elinks: Implementation of shedlock for elinks scheduler
```
[ ] Yes
[ x] No
```

[RDCC-6704]elinks: Implementation of shedlock for elinks scheduler

---

src/integrationTest/resources/db/testmigration/V1_57__elinks_alter.sql
src/main/resources/db/migration/V1_57__elinks_alter.sql

https://tools.hmcts.net/jira/browse/RDCC-6627
```
[ ] Yes
[X] No
```

eLinks : Data model changes to support eLinks V5.0 API specifications

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6755
```
[ ] Yes
[X] No
```

JRD: Test Cases can be clubbed as Parameterised tests

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-550
fix CVE-2023-20883
```
[ ] Yes
[x] No
```

DTSRD-554: fix CVE-2023-20883

---

config/owasp/suppressions.xml
src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6779
```
[ ] Yes
[X] No
```

Mutation test coverage

---

src/main/resources/db/migration/V1_67__elinks_alter_tables.sql
src/main/resources/db/migration/V1_68__elinks_insert_judicial_location_mapping_tables.sql

https://tools.hmcts.net/jira/browse/RDCC-6892
https://tools.hmcts.net/jira/browse/RDCC-6893
```
[ ] Yes
[X] No
```

flyway script

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/DeletedIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedApiPublishingStatusEndToEndIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedForExtraBaseLocationIdEndToEndIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java
src/integrationTest/resources/db/testmigration/V1_61__alter_judicial_user_profile_extracted_date.sql
src/integrationTest/resources/db/testmigration/V1_66__elinks_alter_tables.sql
src/integrationTest/resources/wiremock_responses/deleted.json
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/DeleteRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/ResultsRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/response/DeletedResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/response/ElinksDeleteApiResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/UserProfile.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/feign/ElinksFeignClient.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/DataloadSchedularAuditRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/ElinkDeletedWrapperResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/ELinksService.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksControllerTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobSchedulerTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksDeletedServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6891
```
[ ] Yes
[X] No
```

elinks - delete API

---

build.gradle
config/owasp/suppressions.xml

CVE suppression  CVE-2023-34034

---

src/integrationTest/resources/db/testmigration/V1_52__elinks_alter_tables.sql
src/integrationTest/resources/db/testmigration/V1_72__elinks_insert_jrd_lrd_region_mapping.sql
src/main/resources/db/migration/V1_72__elinks_insert_jrd_lrd_region_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-6929
```
[ ] Yes
[X] No
```

eLinks: Region Mapping Update

---

config/owasp/suppressions.xml

suppress cve
```
[ ] Yes
[x ] No
```

Rdcc suppress CVE

---

charts/rd-judicial-api/values.yaml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksAuthorisationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForObjectId.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationPartialTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedForExtraBaseLocationIdEndToEndIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_75__elinks_insert_jrd_lrd_region_mapping.sql
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/ResultsRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/feign/ElinksFeignClient.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/response/UserSearchResponseWrapperTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RequestUtilsTest.java

https://tools.hmcts.net/jira/browse/RDCC-6997
```
[ ] Yes
[X] No
```

eLinks: Merge code to Master

---

src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/JrdElinkController.java

swagger response document change for refresh api 
```
[ ] Yes
[ x] No
```

refresh api swagger change response

---

src/integrationTest/resources/db/testmigration/V1_79__elinks_insert_jrd_lrd_region_mapping.sql
src/main/resources/db/migration/V1_77__elinks_insert_jrd_lrd_region_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-7001
[ ] Yes
[X] No
```

flyway changes

---

src/integrationTest/resources/application-test.yml
src/integrationTest/resources/templates/simple-template-userProfile.ftl
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/main/resources/templates/simple-template-userProfile.ftl
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java

eLinks-mails: one Personal code having multiple Object Ids & vice-versa

---

charts/rd-judicial-api/values.preview.template.yaml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/CheckForSearchV2UsersIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/UserSearchRequest.java

https://tools.hmcts.net/jira/browse/RDCC-7007
```
[ ] Yes
[X] No
```

eLinks: Expand the supported character list in Type-ahead API

---

.github/renovate.json
renovate.json

- Updating renovate config.
https://tools.hmcts.net/jira/browse/DTSRD-1220
```
[ ] Yes
[x] No
```

DTSRD-1220

---

config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/CheckForSearchV2UsersIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/JudicialReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/JrdElinkController.java

https://tools.hmcts.net/jira/browse/RDCC-7075

content type changes

---

infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-1256 Upgrade postgres to V15

---

src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/IdamElasticSearchIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LeaversIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java
src/integrationTest/resources/application-test.yml
src/integrationTest/resources/wiremock_responses/idamResponsefromObjectId.json
src/integrationTest/resources/wiremock_responses/people.json
src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/LaunchDarklyConfiguration.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksController.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ProfileRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/ElinkIdamWrapperResponse.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/IdamElasticSearchService.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/FeatureToggleServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksControllerTest.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-7073
- [NO] Does this PR introduce a breaking change

eLinks: Additional call to IDAM to fetch SIDAM Id

---

infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-1256.Postgres upgrade v15

---

Jenkinsfile_CNP
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-1466. Remove branches to sync -judicial demo and master 

---

Jenkinsfile_CNP

* TEST COMMIT
* TEST COMMIT
* DTSRD-1466.Remove branches to sync -judicial demo and master

DTSRD-1466. Remove branches to sync -judicial demo 

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/DTSRD-1258

DTSRD-1258.Upgrade to postgres V15 . - merge demo to perftest

---

Jenkinsfile_CNP
build.gradle
src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderV2Test.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksAuthorisationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForExistingObjectId.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForObjectId.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForSidamIdisPresent.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationPartialTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedApiPublishingStatusEndToEndIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedForExtraBaseLocationIdEndToEndIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksLoadPeopleDataWithDuplicate.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_87__elinks_alter_judicial_additional_role.sql
src/integrationTest/resources/wiremock_responses/people.json
src/integrationTest/resources/wiremock_responses/people_del.json
src/integrationTest/resources/wiremock_responses/people_duplicate.json
src/integrationTest/resources/wiremock_responses/people_duplicateobject.json
src/integrationTest/resources/wiremock_responses/people_null_appointmentId.json
src/integrationTest/resources/wiremock_responses/people_part.json
src/integrationTest/resources/wiremock_responses/people_test.json
src/integrationTest/resources/wiremock_responses/testpeople_withoutsidam.json
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/RoleRequest.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/JudicialRoleType.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinkUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
src/main/resources/db/migration/V1_85__elinks_alter_judicial_additional_role.sql
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java

merging changes from master to ithc

---

config/owasp/suppressions.xml

suppress CVE-2023-5590

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-1456.suppressing as no known netty handler version available without vulnerability

---

config/owasp/suppressions.xml
src/integrationTest/resources/db/testmigration/V1_88__elinks_insert_jrd_lrd_region_mapping.sql
src/main/resources/db/migration/V1_86__elinks_insert_jrd_lrd_region_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-7109

insert queries

---

charts/rd-judicial-api/values.preview.template.yaml
src/integrationTest/resources/db/testmigration/V1_89__elinks_insert_jrd_lrd_region_mapping.sql
src/main/resources/db/migration/V1_87__elinks_insert_jrd_lrd_region_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-7167

eLinks : Region Mapping Update

---

src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java
src/main/resources/application.yaml

DTSRD-1466.Updating schema parameter with hibernate

---

charts/rd-judicial-api/values.preview.template.yaml

values.preview resetting

---

build.gradle
charts/rd-judicial-api/values.preview.template.yaml
charts/rd-judicial-api/values.yaml
config/owasp/suppressions.xml
src/main/resources/application.yaml
src/main/resources/db/migration/V1_88__elinks_grant_access_dbjudicialdata

Rdcc get access

---

config/owasp/suppressions.xml

Suppresses CVE-2023-36052 (likely a false positive)

Suppresses CVE-2023-36052

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.yaml
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

Dtsrd-1257. correcting DB_READER_USERNAME

---

charts/rd-judicial-api/values.preview.template.yaml
src/integrationTest/resources/db/testmigration/V1_92__elinks_alter_judicial_user_profile.sql
src/integrationTest/resources/wiremock_responses/people.json
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/UserProfile.java
src/main/resources/application.yaml
src/main/resources/db/migration/V1_91__elinks_alter_judicial_user_profile.sql

https://tools.hmcts.net/jira/browse/RDCC-7237

eLinks : Data model changes for eLinks V5.0

---

src/integrationTest/resources/db/testmigration/V1_94__elinks_jrd_lrd_region.sql
src/main/resources/db/migration/V1_92__elinks_insert_jrd_lrd_region_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-7158

eLinks : Region Mapping Update for eLinks Go-Live

---

build.gradle
config/owasp/suppressions.xml
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

Upgrading perftest branch to V16 and adding subnet_suffix

---

src/integrationTest/resources/db/testmigration/V1_95__elinks_jrd_lrd_region.sql
src/main/resources/db/migration/V1_93__elinks_insert_jrd_lrd_region_mapping.sql

https://tools.hmcts.net/jira/browse/RDCC-7267

elinks : location mapping table update

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-1893.Upgrading main branch to V16 and adding subnet_suffix 

---

src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java

https://tools.hmcts.net/jira/browse/RDCC-7276
correcting error message

correcting error message

---

config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/DeletedIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForExistingObjectId.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForSidamIdisPresent.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksSsoidEndIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LeaversIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_93__insert_judicial_user_profile.sql
src/integrationTest/resources/wiremock_responses/idamResponsefromSsoId.json
src/integrationTest/resources/wiremock_responses/testssoid_people.json
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ProfileRepository.java

https://tools.hmcts.net/jira/browse/RDCC-7224

ssoid sidam update with or without null

---

src/integrationTest/resources/db/testmigration/V1_96__elinks_insert_service_code_mapping.sql
src/main/resources/db/migration/V1_94__elinks_insert_service_code_mapping.sql

Add Family Winger Authorisation code

---

infrastructure/main.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-2065.Adding force_user_permissions_trigger to get access to DTS JIT Access rd DB Reader SC

---

src/integrationTest/resources/db/testmigration/V1_97__elinks_insert_service_code_mapping.sql
src/main/resources/db/migration/V1_95__elinks_insert_service_code_mapping.sql

DTSAM-132: Enable 2 new authorisation for Magistrate access in Private Law

---

src/integrationTest/resources/db/testmigration/V1_98_delete_service_code_mapping.sql
src/main/resources/db/migration/V1_96_delete_service_code_mapping.sql

https://tools.hmcts.net/jira/browse/DTSRD-2214

DTSRD-2214:remove First Tier - Social Entitlement judges (ticket code 376) from the list.

---

infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-2065-3. SCHEMA OWNER FIX

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.yaml

DTSRD-2442: PI33 Configure spot instances in non-production

---

charts/rd-judicial-api/Chart.yaml

DTSRD-2525: Upgrade chat version

---

charts/rd-judicial-api/Chart.yaml
src/main/resources/db/migration/V1_88__elinks_grant_access_dbjudicialdata.sql
src/main/resources/db/migration/V1_97__elinks_grant_access_dbjudicialdata.sql

Create user role if not exists

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

Fix azure extensions

---

audit.json

fixing nightly builds zaproxy error

---

charts/rd-judicial-api/values.yaml
infrastructure/main.tf
infrastructure/terraform.tf
src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java

DTSRD-2750.decommissioning single server

---

build.gradle

Fix db migration issues

---

infrastructure/terraform.tf

Update terraform.tf - upgrading azurerm version

---

charts/rd-judicial-api/Chart.yaml
charts/rd-judicial-api/values.yaml

Disable spot instances

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSRD-2809
- Updated Dependency check
- removed no longer relevant CVE suppressions

DTSRD-2809

---

build.gradle

Update build.gradle to Fix builds

---

build.gradle

Update build.gradle. Fix Build

---

src/main/resources/testcontainers.properties

Testcontainers.org configuration moved to Jenkins builds

Cleanup - delete testcontainers.properties

---

src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ProfileRepository.java
src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImpl.java
src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java

https://tools.hmcts.net/jira/browse/DTSRD-3262

DTSRD-3262: Update missing SIDAM Id's of all judicial users

---

README.md

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

Trigger pipeline build

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-3477
Fix local DependencyCheck, version upgraded to 10.0.3

DTSRD-3477 Fix local DependencyCheck, version upgraded to 10.0.3

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-2029
eLinks : Post-Production - Flyway Config

DTSRD-2029 eLinks : Post-Production - Flyway Config

---

.github/workflows/swagger.yml
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/docs/SwaggerPublisherTest.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSRD-3562
Swagger Publishing

DTSRD-3562 Swagger Publishing

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-3583
Mutation Tests BootClassPathSupported False Error - junit5PluginVersion upgraded 1.0.0 -> 1.2.1 to try to prevent error in the future

DTSRD-3583 Mutation Tests BootClassPathSupported False Error 

---

src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/SendEmailTest.java

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

dummy space to trigger build

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CME-249
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

CME-249: Disable sync to ITHC for database monitoring testing

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/CME-249
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

CME-249: Database monitoring and alerting on RD repositories

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderV2Test.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksRefreshUserProfileIntegrationTestAudit.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ELinksBaseIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/AuthorizationEnabledIntegrationTest.java

https://tools.hmcts.net/jira/browse/DTSRD-4065
Update spring-boot to 3.4.1

DTSRD-4065

---

charts/rd-judicial-api/Chart.yaml

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

RefData Helm OCI Update rd-judicial-api

---

build.gradle

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

Fix build failing as its not able to fetch hmcts lib
